
name: devEnv_osrc_swdev
networks:
  devEnv:
    driver: bridge
    name: devEnv

services:
  python:
    build:
      context: ..
      dockerfile_inline: |
        FROM python:3.11.12-alpine3.21

        RUN mkdir /app
        WORKDIR /app

        COPY __backend .

        RUN python3 -m pip install --upgrade pip
        RUN python3 -m pip install -r requirements.txt

        EXPOSE 8000

        CMD ["sh", "-c", "python3 manage.py migrate ; python3 manage.py createsuperuser --noinput ; python3 manage.py runserver 0.0.0.0:8000"]
    container_name: devEnv_python
    environment:
      TZ: Asia/Ho_Chi_Minh
      SHELL: /bin/sh
      SECRET_KEY: jM4Y3QWw5D0GhY09TG-9DEFuCrC5GDsGAj-8B8fbwK6U8mY_QNu5BhdN1aOKtUwlSIE
      DEBUG: 'True'
      ALLOWED_HOSTS: localhost, 127.0.0.1, 0.0.0.0
      CORS_ALLOWED_ORIGINS: http://localhost:49084, http://localhost:8000
      ADMIN_URL: admin/
      POSTGRES_DB: spotify_db
      POSTGRES_USER: user0
      POSTGRES_PASSWORD: HeLlo|12
      POSTGRES_HOST: devEnv_postgres
      POSTGRES_PORT: 5432
      DOCKER_ENV: 'True'
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
    networks:
      - devEnv
    ports:
      - 49088:8000
    volumes:
      - bdf0:/app/media

  node:
    build:
      context: ..
      dockerfile_inline: |
        FROM node:20.19.1-alpine3.21

        RUN mkdir /app
        WORKDIR /app

        COPY __frontend .

        RUN npm install

        EXPOSE 8000

        CMD ["npm", "run", "dev"]
    container_name: devEnv_node
    environment:
      TZ: Asia/Ho_Chi_Minh
      SHELL: /bin/bash
      POSTGRES_DB: spotify_db
      POSTGRES_HOST: localhost
      POSTGRES_USER: user0
      POSTGRES_PASSWORD: HeLlo|12
      POSTGRES_PORT: 49052
    networks: 
      - devEnv
    ports:
      - 49084:8000

  postgres:
    container_name: devEnv_postgres
    environment:
      TZ: Asia/Ho_Chi_Minh
      SHELL: /bin/bash
      POSTGRES_DB: spotify_db
      POSTGRES_USER: user0
      POSTGRES_PASSWORD: HeLlo|12
    image: postgres:15.12-alpine3.21
    networks:
      - devEnv
    ports:
      - 49052:5432
    volumes:
      - bdb0:/var/lib/postgresql/data
      - ./psql:/docker-entrypoint-initdb.d

  adminer:
    container_name: devEnv_adminer
    image: adminer:4.17.1-standalone
    environment:
      TZ: Asia/Ho_Chi_Minh
      SHELL: /bin/bash
      ADMINER_DEFAULT_SERVER: devEnv_postgres:5432
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_USERNAME: user0
      ADMINER_DEFAULT_PASSWORD: HeLlo|12
      ADMINER_DEFAULT_DB: spotify_db
    networks:
      - devEnv
    ports:
      - 49096:8080

volumes:
  bdf0:
    name: devEnv_bdf0
  bdb0:
    name: devEnv_bdb0