# Generated by Django 4.1.5 on 2025-05-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='user.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='tracks', to='track.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='track.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='user.profile'),
        ),
    ]
