# Generated by Django 4.1.5 on 2025-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='track/video/'),
        ),
    ]
